// export const protocol = "http://"
// export const RootApi = ".localhost:8000"
// export const NoDomainRootApi = "localhost:8000"

export const protocol = "https://"
//export const tenant = "apitest"
// export const tenant = "apitestsec"
export const tenant = "apibrains"
export const RootApi = ".e-conneq.com"
// export const NoDomainRootApi = "e-conneq.com"